server:
  port: 8083

spring:
  application:
    name: payment-service

services:
  order-service:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
